# Generated by Django 5.1.3 on 2025-05-13 06:09

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_name_user_second_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
