# Generated by Django 5.1.3 on 2025-05-17 06:07

import user.post_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_post_mediaitem_postcomment_postlike_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=models.FileField(max_length=500, upload_to=user.post_models.get_file_path),
        ),
    ]
